# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43ffa2c8b47647a7995433079f627764080d043f472d8a97eca979b34003f1ebb4c3e2a088457b53cc6fd6bd9def3f4f5d1d56cd66bf31715529d3b227aa8d24

test:
  secret_key_base: 5587f47b5545c16aa567abee67ec9d5d74cad2d417ba5ec5babc7d3ffae46d9140d4312dc0d8172fd8dd3bc519cffe89f155a4c5787ed3ba4470a1f944e36735

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
